# Initialization

In [1]:
from pypdf import PdfReader
from pathlib import Path
import pandas as pd
import os
import warnings
warnings.simplefilter('ignore')
_p=Path(os.getcwd())
p=_p.parent

# For Nightingale2002

In [2]:
hw=[]
ids=[]
for i in os.listdir(p.parent/'data/Nightingale2002/raw/pdf-reports'):
  reader = PdfReader(p.parent/'data/Nightingale2002/raw/pdf-reports'/i)
  page=reader.pages[1]
  line=page.extract_text()
  ids+=[i[2:6]]
  hw+=[s for s in line.splitlines() if s.startswith("Weight:")]

df2002=pd.DataFrame({'test_id':ids,'height_weight':hw})
df2002['weight'] = df2002['height_weight'].str.extract(r'Weight:\s*(\d+|N/A)')
df2002['height'] = df2002['height_weight'].str.extract(r'Height:\s*(\d+|N/A)')
df2002['weight'] = pd.to_numeric(df2002['weight'], errors='coerce')
df2002['height'] = pd.to_numeric(df2002['height'], errors='coerce')
df2002.drop(columns=['height_weight'], inplace=True)
df2002

    test_id  weight  height
0      4385     NaN     NaN
1      4386     NaN     NaN
2      4387     NaN     NaN
3      4388     NaN     NaN
4      4389     NaN     NaN
..      ...     ...     ...
98     6488     NaN     NaN
99     6489     NaN     NaN
100    6490     NaN     NaN
101    6491     NaN     NaN
102    6492     NaN     NaN

[103 rows x 3 columns]

In [3]:
df2002.dropna()

   test_id  weight  height
6     4391   556.0   158.0
7     4392   556.0   158.0
8     4393   556.0   158.0
9     4394   556.0   158.0
10    4395   556.0   158.0
11    4396   556.0   158.0
12    4397   556.0   158.0
13    4398   556.0   158.0

# For Nightingale2007

In [4]:
hw=[]
ids=[]
for i in os.listdir(p.parent/'data/Nightingale2007/raw/pdf-reports'):
  reader = PdfReader(p.parent/'data/Nightingale2007/raw/pdf-reports'/i)
  page=reader.pages[1]
  line=page.extract_text()
  ids+=[i[2:6]]
  hw+=[s for s in line.splitlines() if s.startswith("Weight:")]

df2007=pd.DataFrame({'test_id':ids,'height_weight':hw})
df2007['weight'] = df2007['height_weight'].str.extract(r'Weight:\s*(\d+|N/A)')
df2007['height'] = df2007['height_weight'].str.extract(r'Height:\s*(\d+|N/A)')
df2007['weight'] = pd.to_numeric(df2007['weight'], errors='coerce')
df2007['height'] = pd.to_numeric(df2007['height'], errors='coerce')
df2007.drop(columns=['height_weight'], inplace=True)
df2007

    test_id  weight  height
0      6355     NaN     NaN
1      6356     NaN     NaN
2      6357     NaN     NaN
3      6358     NaN     NaN
4      6359     NaN     NaN
..      ...     ...     ...
123    7504     NaN     NaN
124    7505     NaN     NaN
125    7506     NaN     NaN
126    7507     NaN     NaN
127    7508     NaN     NaN

[128 rows x 3 columns]

In [5]:
df2007.dropna()

Empty DataFrame
Columns: [test_id, weight, height]
Index: []